<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>author</key>
	<string>Frank Niu</string>
	<key>bundleUUID</key>
	<string>EB590797-FBEE-4BEA-A140-8339AFD2CE1B</string>
	<key>comment</key>
	<string>ALE syntax highlight</string>
	<key>fileTypes</key>
	<array>
		<string>pl</string>
		<string>plt</string>
	</array>
	<key>name</key>
	<string>ale</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(% PYTHON_FUNC_START)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.ale</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Python code block</string>
			<key>end</key>
			<string>(?=(% PYTHON_FUNC_END))</string>
			<key>name</key>
			<string>template.code-block.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(% PYTHON_LINE_CHECK_START)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.ale</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Python code block</string>
			<key>end</key>
			<string>(?=(% PYTHON_LINE_CHECK_END))</string>
			<key>name</key>
			<string>template.code-block.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lists</string>
			<key>name</key>
			<string>list.ale</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>('?[\w|\\']+'?\s+)(---&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.atom.simple.ale</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ale</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Lexical entries</string>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.ale</string>
				</dict>
			</dict>
			<key>name</key>
			<string>lexical-entry.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cat_entry</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([[:alpha:]_][[:alnum:]_]*)\s+(rule)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ale</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.ale</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Phrase rule</string>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.ale</string>
				</dict>
			</dict>
			<key>name</key>
			<string>phrase-rule.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cat_entry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#goal_calling</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(cat|goal)\b&gt;|===&gt;</string>
					<key>name</key>
					<string>storage.type.struct.ale</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([[:alpha:]_][[:alnum:]_]*)\s+(lex_rule)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.function.ale</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.ale</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Lexical rule</string>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.ale</string>
				</dict>
			</dict>
			<key>name</key>
			<string>lex-rule.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cat_entry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#when_pattern</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(\*\*&gt;|morphs|if|becomes)\b</string>
					<key>name</key>
					<string>storage.type.function</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\w+)\s+(?=(sub|intro))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.function.ale</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Defining types</string>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.ale</string>
				</dict>
			</dict>
			<key>name</key>
			<string>type.definition.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(sub)\b\s+\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>type.definition.sublist.ale</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#type_list_item</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(intro)\b\s+\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>type.definition.intro.ale</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#feature_list_item</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#goal_calling</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(if)\s+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.ale</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Defining goals</string>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.ale</string>
				</dict>
			</dict>
			<key>name</key>
			<string>goal.definition.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>contentName</key>
					<string>goal.name.ale</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#goal_calling</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>cat_entry</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>cat_entry.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#type_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_arguments</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ale</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.line.note.notation.ale</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(%+)\s*(BUG|FIXME|TODO).*$</string>
					<key>name</key>
					<string>comment.line.note.ale</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.ale</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(%+).*$</string>
					<key>name</key>
					<string>comment.line.number-sign.ale</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|bot|top)\b</string>
			<key>name</key>
			<string>constant.language.ale</string>
		</dict>
		<key>feature_list_item</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ale</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.annotation.ale</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.ale</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*(:)\s*(\w+)</string>
		</dict>
		<key>goal_calling</key>
		<dict>
			<key>begin</key>
			<string>([[:alpha:]_][[:alnum:]_]*)\s*(?=(\())</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.function.ale</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.ale</string>
				</dict>
			</dict>
			<key>name</key>
			<string>goal.call.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.ale</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.function-call.arguments.ale</string>
					<key>end</key>
					<string>(?=(\)))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.ale</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variable_arguments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lists</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cat_entry</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type_value</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>lists</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.begin.ale</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.end.ale</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\,|\|)</string>
					<key>name</key>
					<string>punctuation.separator.parameters.ale</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable_arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#cat_entry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_value</string>
				</dict>
			</array>
		</dict>
		<key>type_list_item</key>
		<dict>
			<key>match</key>
			<string>\w+</string>
			<key>name</key>
			<string>constant.other.atom.simple.ale</string>
		</dict>
		<key>type_value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.ale</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w+)\:\s*</string>
				</dict>
			</array>
		</dict>
		<key>variable_arguments</key>
		<dict>
			<key>match</key>
			<string>\b[A-Z]\w*</string>
			<key>name</key>
			<string>variable.parameter.uppercase.ale</string>
		</dict>
		<key>when_pattern</key>
		<dict>
			<key>begin</key>
			<string>(when)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(\.|,))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.ale</string>
				</dict>
			</dict>
			<key>name</key>
			<string>when_pattern.ale</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#goal_calling</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ale</string>
	<key>uuid</key>
	<string>11B0273F-0284-4483-B17B-4B8D0A9294CC</string>
</dict>
</plist>
