<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>trale</string>
    </array>
    <key>name</key>
    <string>trale</string>
    <key>patterns</key>
    <array>

        <dict>
            <key>match</key>
            <string>\b(sub|cat|rule|intro)\b</string>
            <key>name</key>
            <string>keyword.control.trale</string>
        </dict>

        <!-- lexicon -->
        <dict>
            <key>begin</key>
            <string>(\w+\s+)(--->)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.function-call.trale</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.trale</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(\.)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.parameters.end.trale</string>
                </dict>

                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.arguments.end.trale</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.function.trale</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(\w)</string>
                    <key>name</key>
                    <string>variable.parameter.trale</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\()</string>
                    <key>name</key>
                    <string>punctuation.section.parameters.begin.trale</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\))</string>
                    <key>name</key>
                    <string>punctuation.section.parameters.end.trale</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(,)</string>
                    <key>name</key>
                    <string>punctuation.separator.parameters.trale</string>
                </dict>  
                <dict>
                    <key>match</key>
                    <string>(\w*)(:)(\w*)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.trale</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.annotation.trale</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>variable.value.trale</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>

        <!-- decl -->
        <dict>
            <key>begin</key>
            <string>(\w+\s+)(sub)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.function-call.trale</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.trale</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\.</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.arguments.end.trale</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.function.trale</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(intro)</string>
                    <key>name</key>
                    <string>keyword.control.trale</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>([\[\]])</string>
                    <key>name</key>
                    <string>punctuation.section.parameters</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\w*)</string>
                    <key>name</key>
                    <string>variable.parameter.trale</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\w*)(:)(\w*)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.trale</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.annotation.trale</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>variable.value.trale</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>

        <!-- rules -->
        <dict>
            <key>begin</key>
            <string>(\w+\s+)(rule)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>meta.function-call.trale</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.trale</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\.</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.section.arguments.end.trale</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.function.trale</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>%</string>
                    <key>end</key>
                    <string>$</string>
                    <key>name</key>
                    <string>comment.line.trale</string>
                    <key>patterns</key>
                    <array/>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(===>)</string>
                    <key>name</key>
                    <string>keyword.control.trale</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(cat)(>)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.trale</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.operand.trale</string>
                        </dict>
                    </dict>
                </dict>
                <dict>
                    <key>match</key>
                    <string>([\(\)])</string>
                    <key>name</key>
                    <string>punctuation.section.parameters</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>([A-Z]\w*)</string>
                    <key>name</key>
                    <string>support.type.trale</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\w*)</string>
                    <key>name</key>
                    <string>variable.value.trale</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>(\w*)(:)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.trale</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.separator.annotation.trale</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>variable.value.trale</string>
                        </dict>
                    </dict>
                </dict>
            </array>
        </dict>

        <dict>
            <key>begin</key>
            <string>%</string>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>comment.line.trale</string>
            <key>patterns</key>
            <array/>
        </dict>

        <dict>
            <key>match</key>
            <string>\b\d*\b</string>
            <key>name</key>
            <string>constant.numeric.trale</string>
        </dict>

        <dict>
            <key>match</key>
            <string>"[^"]*"</string>
            <key>name</key>
            <string>string.trale</string>
        </dict>

    </array>
    <key>repository</key>
    <dict/>
    <key>scopeName</key>
    <string>source.trale</string>
    <key>uuid</key>
    <string>07629b98-022c-4204-a227-aa65ae352fab</string>
</dict>
</plist>
